//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StdSevice
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StdSevice.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enrollmentQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> enrollmentQueryAsync(string queryBy, string skey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enrollmentQuery03", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StdSevice.ArrayOfXElement> enrollmentQuery03Async(string queryBy, string skey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enrollmentQuery01", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> enrollmentQuery01Async(string strKeyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enrollmentQuery02", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> enrollmentQuery02Async(string strKeyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStdNoInfoByMaxYYM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StdSevice.clsStdmInfo> getStdNoInfoByMaxYYMAsync(string sToken, string stdno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStdNoInfoByMaxYYM01", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StdSevice.clsStdmInfo> getStdNoInfoByMaxYYM01Async(string sToken, string stdno, string sRegiCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStdNoInfoByMaxYYMForMiFare", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StdSevice.clsDataResult> getStdNoInfoByMaxYYMForMiFareAsync(string sToken, string stdno, string sRegiCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStdNoInfoByMaxYYMChkRegiCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StdSevice.clsStdmInfo> getStdNoInfoByMaxYYMChkRegiCodeAsync(string sToken, string stdno, string regicode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insTbsaaCardBlockInfoLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> insTbsaaCardBlockInfoLogAsync(string sToken, string cardNo, string AType, string s56, string s57, string s58, string s59);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getdept", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StdSevice.ArrayOfXElement> getdeptAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStaffInfoForUDollar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StdSevice.clsStaffInfoForUDollar> getStaffInfoForUDollarAsync(string sToken, string psnno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStdNoInfoByMaxYYMForUDollar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StdSevice.clsStdmInfoForUDollar> getStdNoInfoByMaxYYMForUDollarAsync(string sToken, string stdno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStdNoInfoByMaxYYMForAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StdSevice.clsStdmInfoForAD> getStdNoInfoByMaxYYMForADAsync(string sToken, string stdno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStaffInfoForAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StdSevice.clsStaffInfoForAD> getStaffInfoForADAsync(string sToken, string psnno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCardInfoForMiFare", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StdSevice.clsCardHistResult> getCardInfoForMiFareAsync(string sToken, string sKind, string stdno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insUpdateTBSAACardIDForMiFare", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> insUpdateTBSAACardIDForMiFareAsync(string sToken, string sInsUpdate, StdSevice.clsCardHistInfo clsCardInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isMyStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> isMyStudentAsync(string sToken, string stdno);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsCardHistInfo
    {
        
        private string clsPIDField;
        
        private string clsNoField;
        
        private string clsHistoryField;
        
        private string clsVersiionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clsPID
        {
            get
            {
                return this.clsPIDField;
            }
            set
            {
                this.clsPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string clsNo
        {
            get
            {
                return this.clsNoField;
            }
            set
            {
                this.clsNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string clsHistory
        {
            get
            {
                return this.clsHistoryField;
            }
            set
            {
                this.clsHistoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string clsVersiion
        {
            get
            {
                return this.clsVersiionField;
            }
            set
            {
                this.clsVersiionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsCardHistResult
    {
        
        private bool bErrorField;
        
        private bool bResultIsValidField;
        
        private string sMsgField;
        
        private clsCardHistInfo clsCardHInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool bError
        {
            get
            {
                return this.bErrorField;
            }
            set
            {
                this.bErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool bResultIsValid
        {
            get
            {
                return this.bResultIsValidField;
            }
            set
            {
                this.bResultIsValidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sMsg
        {
            get
            {
                return this.sMsgField;
            }
            set
            {
                this.sMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public clsCardHistInfo clsCardHInfo
        {
            get
            {
                return this.clsCardHInfoField;
            }
            set
            {
                this.clsCardHInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsStaffInfoForAD
    {
        
        private string sPsnNoField;
        
        private string sChnNameField;
        
        private string sIDNoField;
        
        private string sPassWdField;
        
        private string sUnitField;
        
        private string sChnAbbrField;
        
        private string sPosiField;
        
        private string sPosiChnNameField;
        
        private string sBDateField;
        
        private string sCardNoField;
        
        private string sCardVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sPsnNo
        {
            get
            {
                return this.sPsnNoField;
            }
            set
            {
                this.sPsnNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sChnName
        {
            get
            {
                return this.sChnNameField;
            }
            set
            {
                this.sChnNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sIDNo
        {
            get
            {
                return this.sIDNoField;
            }
            set
            {
                this.sIDNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sPassWd
        {
            get
            {
                return this.sPassWdField;
            }
            set
            {
                this.sPassWdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sUnit
        {
            get
            {
                return this.sUnitField;
            }
            set
            {
                this.sUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sChnAbbr
        {
            get
            {
                return this.sChnAbbrField;
            }
            set
            {
                this.sChnAbbrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sPosi
        {
            get
            {
                return this.sPosiField;
            }
            set
            {
                this.sPosiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string sPosiChnName
        {
            get
            {
                return this.sPosiChnNameField;
            }
            set
            {
                this.sPosiChnNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string sBDate
        {
            get
            {
                return this.sBDateField;
            }
            set
            {
                this.sBDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string sCardNo
        {
            get
            {
                return this.sCardNoField;
            }
            set
            {
                this.sCardNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string sCardVersion
        {
            get
            {
                return this.sCardVersionField;
            }
            set
            {
                this.sCardVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsStdmInfoForAD
    {
        
        private string sStdNoField;
        
        private string sChnNameField;
        
        private string sIDNoField;
        
        private string sPassWdField;
        
        private string sDeptField;
        
        private string sYCGField;
        
        private string sMaxYYMField;
        
        private string sCabbrField;
        
        private string sChndeptField;
        
        private string sWhdrYYMField;
        
        private string sWhdrReasonField;
        
        private string sBDateField;
        
        private string sEDateField;
        
        private string sCardNoField;
        
        private string sCardVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sStdNo
        {
            get
            {
                return this.sStdNoField;
            }
            set
            {
                this.sStdNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sChnName
        {
            get
            {
                return this.sChnNameField;
            }
            set
            {
                this.sChnNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sIDNo
        {
            get
            {
                return this.sIDNoField;
            }
            set
            {
                this.sIDNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sPassWd
        {
            get
            {
                return this.sPassWdField;
            }
            set
            {
                this.sPassWdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sDept
        {
            get
            {
                return this.sDeptField;
            }
            set
            {
                this.sDeptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sYCG
        {
            get
            {
                return this.sYCGField;
            }
            set
            {
                this.sYCGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sMaxYYM
        {
            get
            {
                return this.sMaxYYMField;
            }
            set
            {
                this.sMaxYYMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string sCabbr
        {
            get
            {
                return this.sCabbrField;
            }
            set
            {
                this.sCabbrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string sChndept
        {
            get
            {
                return this.sChndeptField;
            }
            set
            {
                this.sChndeptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string sWhdrYYM
        {
            get
            {
                return this.sWhdrYYMField;
            }
            set
            {
                this.sWhdrYYMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string sWhdrReason
        {
            get
            {
                return this.sWhdrReasonField;
            }
            set
            {
                this.sWhdrReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string sBDate
        {
            get
            {
                return this.sBDateField;
            }
            set
            {
                this.sBDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string sEDate
        {
            get
            {
                return this.sEDateField;
            }
            set
            {
                this.sEDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string sCardNo
        {
            get
            {
                return this.sCardNoField;
            }
            set
            {
                this.sCardNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string sCardVersion
        {
            get
            {
                return this.sCardVersionField;
            }
            set
            {
                this.sCardVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsStdmInfoForUDollar
    {
        
        private string sStdNoField;
        
        private string sChnNameField;
        
        private string sIDNoField;
        
        private string sDeptField;
        
        private string sYCGField;
        
        private string sMaxYYMField;
        
        private string sCabbrField;
        
        private string sChndeptField;
        
        private string sWhdrYYMField;
        
        private string sWhdrReasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sStdNo
        {
            get
            {
                return this.sStdNoField;
            }
            set
            {
                this.sStdNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sChnName
        {
            get
            {
                return this.sChnNameField;
            }
            set
            {
                this.sChnNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sIDNo
        {
            get
            {
                return this.sIDNoField;
            }
            set
            {
                this.sIDNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sDept
        {
            get
            {
                return this.sDeptField;
            }
            set
            {
                this.sDeptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sYCG
        {
            get
            {
                return this.sYCGField;
            }
            set
            {
                this.sYCGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sMaxYYM
        {
            get
            {
                return this.sMaxYYMField;
            }
            set
            {
                this.sMaxYYMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sCabbr
        {
            get
            {
                return this.sCabbrField;
            }
            set
            {
                this.sCabbrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string sChndept
        {
            get
            {
                return this.sChndeptField;
            }
            set
            {
                this.sChndeptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string sWhdrYYM
        {
            get
            {
                return this.sWhdrYYMField;
            }
            set
            {
                this.sWhdrYYMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string sWhdrReason
        {
            get
            {
                return this.sWhdrReasonField;
            }
            set
            {
                this.sWhdrReasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsStaffInfoForUDollar
    {
        
        private string sPsnNoField;
        
        private string sChnNameField;
        
        private string sUnitField;
        
        private string sChnAbbrField;
        
        private string sPosiField;
        
        private string sPosiChnNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sPsnNo
        {
            get
            {
                return this.sPsnNoField;
            }
            set
            {
                this.sPsnNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sChnName
        {
            get
            {
                return this.sChnNameField;
            }
            set
            {
                this.sChnNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sUnit
        {
            get
            {
                return this.sUnitField;
            }
            set
            {
                this.sUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sChnAbbr
        {
            get
            {
                return this.sChnAbbrField;
            }
            set
            {
                this.sChnAbbrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sPosi
        {
            get
            {
                return this.sPosiField;
            }
            set
            {
                this.sPosiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sPosiChnName
        {
            get
            {
                return this.sPosiChnNameField;
            }
            set
            {
                this.sPosiChnNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsDataResult
    {
        
        private bool bErrorField;
        
        private bool bResultIsValidField;
        
        private string sMsgField;
        
        private clsStdmInfo clsStdmInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool bError
        {
            get
            {
                return this.bErrorField;
            }
            set
            {
                this.bErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool bResultIsValid
        {
            get
            {
                return this.bResultIsValidField;
            }
            set
            {
                this.bResultIsValidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sMsg
        {
            get
            {
                return this.sMsgField;
            }
            set
            {
                this.sMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public clsStdmInfo clsStdmInfo
        {
            get
            {
                return this.clsStdmInfoField;
            }
            set
            {
                this.clsStdmInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsStdmInfo
    {
        
        private string clsStdNoField;
        
        private string clsChnNameField;
        
        private string clsIDNoField;
        
        private string clsDeptField;
        
        private string clsYCGField;
        
        private string clsMaxYYMField;
        
        private string clsCabbrField;
        
        private string clsChndeptField;
        
        private string clsWhdrYYMField;
        
        private string clsWhdrReasonField;
        
        private string clsBdateField;
        
        private string clsID1Field;
        
        private string clsRegiCodeField;
        
        private string clsCardNoField;
        
        private string clsCardVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clsStdNo
        {
            get
            {
                return this.clsStdNoField;
            }
            set
            {
                this.clsStdNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string clsChnName
        {
            get
            {
                return this.clsChnNameField;
            }
            set
            {
                this.clsChnNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string clsIDNo
        {
            get
            {
                return this.clsIDNoField;
            }
            set
            {
                this.clsIDNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string clsDept
        {
            get
            {
                return this.clsDeptField;
            }
            set
            {
                this.clsDeptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string clsYCG
        {
            get
            {
                return this.clsYCGField;
            }
            set
            {
                this.clsYCGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string clsMaxYYM
        {
            get
            {
                return this.clsMaxYYMField;
            }
            set
            {
                this.clsMaxYYMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string clsCabbr
        {
            get
            {
                return this.clsCabbrField;
            }
            set
            {
                this.clsCabbrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string clsChndept
        {
            get
            {
                return this.clsChndeptField;
            }
            set
            {
                this.clsChndeptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string clsWhdrYYM
        {
            get
            {
                return this.clsWhdrYYMField;
            }
            set
            {
                this.clsWhdrYYMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string clsWhdrReason
        {
            get
            {
                return this.clsWhdrReasonField;
            }
            set
            {
                this.clsWhdrReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string clsBdate
        {
            get
            {
                return this.clsBdateField;
            }
            set
            {
                this.clsBdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string clsID1
        {
            get
            {
                return this.clsID1Field;
            }
            set
            {
                this.clsID1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string clsRegiCode
        {
            get
            {
                return this.clsRegiCodeField;
            }
            set
            {
                this.clsRegiCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string clsCardNo
        {
            get
            {
                return this.clsCardNoField;
            }
            set
            {
                this.clsCardNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string clsCardVersion
        {
            get
            {
                return this.clsCardVersionField;
            }
            set
            {
                this.clsCardVersionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServiceSoapChannel : StdSevice.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<StdSevice.ServiceSoap>, StdSevice.ServiceSoap
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync()
        {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Threading.Tasks.Task<string> enrollmentQueryAsync(string queryBy, string skey)
        {
            return base.Channel.enrollmentQueryAsync(queryBy, skey);
        }
        
        public System.Threading.Tasks.Task<StdSevice.ArrayOfXElement> enrollmentQuery03Async(string queryBy, string skey)
        {
            return base.Channel.enrollmentQuery03Async(queryBy, skey);
        }
        
        public System.Threading.Tasks.Task<string> enrollmentQuery01Async(string strKeyName)
        {
            return base.Channel.enrollmentQuery01Async(strKeyName);
        }
        
        public System.Threading.Tasks.Task<string> enrollmentQuery02Async(string strKeyName)
        {
            return base.Channel.enrollmentQuery02Async(strKeyName);
        }
        
        public System.Threading.Tasks.Task<StdSevice.clsStdmInfo> getStdNoInfoByMaxYYMAsync(string sToken, string stdno)
        {
            return base.Channel.getStdNoInfoByMaxYYMAsync(sToken, stdno);
        }
        
        public System.Threading.Tasks.Task<StdSevice.clsStdmInfo> getStdNoInfoByMaxYYM01Async(string sToken, string stdno, string sRegiCode)
        {
            return base.Channel.getStdNoInfoByMaxYYM01Async(sToken, stdno, sRegiCode);
        }
        
        public System.Threading.Tasks.Task<StdSevice.clsDataResult> getStdNoInfoByMaxYYMForMiFareAsync(string sToken, string stdno, string sRegiCode)
        {
            return base.Channel.getStdNoInfoByMaxYYMForMiFareAsync(sToken, stdno, sRegiCode);
        }
        
        public System.Threading.Tasks.Task<StdSevice.clsStdmInfo> getStdNoInfoByMaxYYMChkRegiCodeAsync(string sToken, string stdno, string regicode)
        {
            return base.Channel.getStdNoInfoByMaxYYMChkRegiCodeAsync(sToken, stdno, regicode);
        }
        
        public System.Threading.Tasks.Task<bool> insTbsaaCardBlockInfoLogAsync(string sToken, string cardNo, string AType, string s56, string s57, string s58, string s59)
        {
            return base.Channel.insTbsaaCardBlockInfoLogAsync(sToken, cardNo, AType, s56, s57, s58, s59);
        }
        
        public System.Threading.Tasks.Task<StdSevice.ArrayOfXElement> getdeptAsync()
        {
            return base.Channel.getdeptAsync();
        }
        
        public System.Threading.Tasks.Task<StdSevice.clsStaffInfoForUDollar> getStaffInfoForUDollarAsync(string sToken, string psnno)
        {
            return base.Channel.getStaffInfoForUDollarAsync(sToken, psnno);
        }
        
        public System.Threading.Tasks.Task<StdSevice.clsStdmInfoForUDollar> getStdNoInfoByMaxYYMForUDollarAsync(string sToken, string stdno)
        {
            return base.Channel.getStdNoInfoByMaxYYMForUDollarAsync(sToken, stdno);
        }
        
        public System.Threading.Tasks.Task<StdSevice.clsStdmInfoForAD> getStdNoInfoByMaxYYMForADAsync(string sToken, string stdno)
        {
            return base.Channel.getStdNoInfoByMaxYYMForADAsync(sToken, stdno);
        }
        
        public System.Threading.Tasks.Task<StdSevice.clsStaffInfoForAD> getStaffInfoForADAsync(string sToken, string psnno)
        {
            return base.Channel.getStaffInfoForADAsync(sToken, psnno);
        }
        
        public System.Threading.Tasks.Task<StdSevice.clsCardHistResult> getCardInfoForMiFareAsync(string sToken, string sKind, string stdno)
        {
            return base.Channel.getCardInfoForMiFareAsync(sToken, sKind, stdno);
        }
        
        public System.Threading.Tasks.Task<bool> insUpdateTBSAACardIDForMiFareAsync(string sToken, string sInsUpdate, StdSevice.clsCardHistInfo clsCardInfo)
        {
            return base.Channel.insUpdateTBSAACardIDForMiFareAsync(sToken, sInsUpdate, clsCardInfo);
        }
        
        public System.Threading.Tasks.Task<bool> isMyStudentAsync(string sToken, string stdno)
        {
            return base.Channel.isMyStudentAsync(sToken, stdno);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ap2.pccu.edu.tw:8888/stdmservice/service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ap2.pccu.edu.tw:8888/stdmservice/service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.1.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
