//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSOAuth
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsWebServiceResult", Namespace="http://pccu.edu.tw")]
    public partial class clsWebServiceResult : object
    {
        
        private bool bErrorField;
        
        private bool bResultIsValidField;
        
        private string sMsgField;
        
        private SSOAuth.SimpleSessionData stndataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool bError
        {
            get
            {
                return this.bErrorField;
            }
            set
            {
                this.bErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool bResultIsValid
        {
            get
            {
                return this.bResultIsValidField;
            }
            set
            {
                this.bResultIsValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sMsg
        {
            get
            {
                return this.sMsgField;
            }
            set
            {
                this.sMsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SSOAuth.SimpleSessionData stndata
        {
            get
            {
                return this.stndataField;
            }
            set
            {
                this.stndataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleSessionData", Namespace="http://pccu.edu.tw")]
    public partial class SimpleSessionData : object
    {
        
        private string userAccountField;
        
        private string userRoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userAccount
        {
            get
            {
                return this.userAccountField;
            }
            set
            {
                this.userAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userRole
        {
            get
            {
                return this.userRoleField;
            }
            set
            {
                this.userRoleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsWebServiceResult2", Namespace="http://pccu.edu.tw")]
    public partial class clsWebServiceResult2 : object
    {
        
        private bool bErrorField;
        
        private bool bResultIsValidField;
        
        private string sMsgField;
        
        private SSOAuth.SimpleSessionDataWithUid stndataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool bError
        {
            get
            {
                return this.bErrorField;
            }
            set
            {
                this.bErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool bResultIsValid
        {
            get
            {
                return this.bResultIsValidField;
            }
            set
            {
                this.bResultIsValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sMsg
        {
            get
            {
                return this.sMsgField;
            }
            set
            {
                this.sMsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SSOAuth.SimpleSessionDataWithUid stndata
        {
            get
            {
                return this.stndataField;
            }
            set
            {
                this.stndataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleSessionDataWithUid", Namespace="http://pccu.edu.tw")]
    public partial class SimpleSessionDataWithUid : object
    {
        
        private string userAccountField;
        
        private string userIDField;
        
        private string userRoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userAccount
        {
            get
            {
                return this.userAccountField;
            }
            set
            {
                this.userAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userRole
        {
            get
            {
                return this.userRoleField;
            }
            set
            {
                this.userRoleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsJSONResult", Namespace="http://pccu.edu.tw")]
    public partial class clsJSONResult : object
    {
        
        private bool bErrorField;
        
        private bool bResultIsValidField;
        
        private string sMsgField;
        
        private string JSONDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool bError
        {
            get
            {
                return this.bErrorField;
            }
            set
            {
                this.bErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool bResultIsValid
        {
            get
            {
                return this.bResultIsValidField;
            }
            set
            {
                this.bResultIsValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sMsg
        {
            get
            {
                return this.sMsgField;
            }
            set
            {
                this.sMsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string JSONData
        {
            get
            {
                return this.JSONDataField;
            }
            set
            {
                this.JSONDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pccu.edu.tw", ConfigurationName="SSOAuth.getIdentitySoap")]
    public interface getIdentitySoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pccu.edu.tw/getSimpleIdentity", ReplyAction="*")]
        System.Threading.Tasks.Task<SSOAuth.getSimpleIdentityResponse> getSimpleIdentityAsync(SSOAuth.getSimpleIdentityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pccu.edu.tw/getSimpleIdentityWithUid", ReplyAction="*")]
        System.Threading.Tasks.Task<SSOAuth.getSimpleIdentityWithUidResponse> getSimpleIdentityWithUidAsync(SSOAuth.getSimpleIdentityWithUidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pccu.edu.tw/getComplexIdentity", ReplyAction="*")]
        System.Threading.Tasks.Task<SSOAuth.getComplexIdentityResponse> getComplexIdentityAsync(SSOAuth.getComplexIdentityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSimpleIdentityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSimpleIdentity", Namespace="http://pccu.edu.tw", Order=0)]
        public SSOAuth.getSimpleIdentityRequestBody Body;
        
        public getSimpleIdentityRequest()
        {
        }
        
        public getSimpleIdentityRequest(SSOAuth.getSimpleIdentityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pccu.edu.tw")]
    public partial class getSimpleIdentityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string securityToken;
        
        public getSimpleIdentityRequestBody()
        {
        }
        
        public getSimpleIdentityRequestBody(string guid, string securityToken)
        {
            this.guid = guid;
            this.securityToken = securityToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSimpleIdentityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSimpleIdentityResponse", Namespace="http://pccu.edu.tw", Order=0)]
        public SSOAuth.getSimpleIdentityResponseBody Body;
        
        public getSimpleIdentityResponse()
        {
        }
        
        public getSimpleIdentityResponse(SSOAuth.getSimpleIdentityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pccu.edu.tw")]
    public partial class getSimpleIdentityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SSOAuth.clsWebServiceResult getSimpleIdentityResult;
        
        public getSimpleIdentityResponseBody()
        {
        }
        
        public getSimpleIdentityResponseBody(SSOAuth.clsWebServiceResult getSimpleIdentityResult)
        {
            this.getSimpleIdentityResult = getSimpleIdentityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSimpleIdentityWithUidRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSimpleIdentityWithUid", Namespace="http://pccu.edu.tw", Order=0)]
        public SSOAuth.getSimpleIdentityWithUidRequestBody Body;
        
        public getSimpleIdentityWithUidRequest()
        {
        }
        
        public getSimpleIdentityWithUidRequest(SSOAuth.getSimpleIdentityWithUidRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pccu.edu.tw")]
    public partial class getSimpleIdentityWithUidRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string securityToken;
        
        public getSimpleIdentityWithUidRequestBody()
        {
        }
        
        public getSimpleIdentityWithUidRequestBody(string guid, string securityToken)
        {
            this.guid = guid;
            this.securityToken = securityToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSimpleIdentityWithUidResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSimpleIdentityWithUidResponse", Namespace="http://pccu.edu.tw", Order=0)]
        public SSOAuth.getSimpleIdentityWithUidResponseBody Body;
        
        public getSimpleIdentityWithUidResponse()
        {
        }
        
        public getSimpleIdentityWithUidResponse(SSOAuth.getSimpleIdentityWithUidResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pccu.edu.tw")]
    public partial class getSimpleIdentityWithUidResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SSOAuth.clsWebServiceResult2 getSimpleIdentityWithUidResult;
        
        public getSimpleIdentityWithUidResponseBody()
        {
        }
        
        public getSimpleIdentityWithUidResponseBody(SSOAuth.clsWebServiceResult2 getSimpleIdentityWithUidResult)
        {
            this.getSimpleIdentityWithUidResult = getSimpleIdentityWithUidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getComplexIdentityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getComplexIdentity", Namespace="http://pccu.edu.tw", Order=0)]
        public SSOAuth.getComplexIdentityRequestBody Body;
        
        public getComplexIdentityRequest()
        {
        }
        
        public getComplexIdentityRequest(SSOAuth.getComplexIdentityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pccu.edu.tw")]
    public partial class getComplexIdentityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string securityToken;
        
        public getComplexIdentityRequestBody()
        {
        }
        
        public getComplexIdentityRequestBody(string guid, string securityToken)
        {
            this.guid = guid;
            this.securityToken = securityToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getComplexIdentityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getComplexIdentityResponse", Namespace="http://pccu.edu.tw", Order=0)]
        public SSOAuth.getComplexIdentityResponseBody Body;
        
        public getComplexIdentityResponse()
        {
        }
        
        public getComplexIdentityResponse(SSOAuth.getComplexIdentityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pccu.edu.tw")]
    public partial class getComplexIdentityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SSOAuth.clsJSONResult getComplexIdentityResult;
        
        public getComplexIdentityResponseBody()
        {
        }
        
        public getComplexIdentityResponseBody(SSOAuth.clsJSONResult getComplexIdentityResult)
        {
            this.getComplexIdentityResult = getComplexIdentityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface getIdentitySoapChannel : SSOAuth.getIdentitySoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class getIdentitySoapClient : System.ServiceModel.ClientBase<SSOAuth.getIdentitySoap>, SSOAuth.getIdentitySoap
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public getIdentitySoapClient(EndpointConfiguration endpointConfiguration) : 
                base(getIdentitySoapClient.GetBindingForEndpoint(endpointConfiguration), getIdentitySoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public getIdentitySoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(getIdentitySoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public getIdentitySoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(getIdentitySoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public getIdentitySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSOAuth.getSimpleIdentityResponse> SSOAuth.getIdentitySoap.getSimpleIdentityAsync(SSOAuth.getSimpleIdentityRequest request)
        {
            return base.Channel.getSimpleIdentityAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSOAuth.getSimpleIdentityResponse> getSimpleIdentityAsync(string guid, string securityToken)
        {
            SSOAuth.getSimpleIdentityRequest inValue = new SSOAuth.getSimpleIdentityRequest();
            inValue.Body = new SSOAuth.getSimpleIdentityRequestBody();
            inValue.Body.guid = guid;
            inValue.Body.securityToken = securityToken;
            return ((SSOAuth.getIdentitySoap)(this)).getSimpleIdentityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSOAuth.getSimpleIdentityWithUidResponse> SSOAuth.getIdentitySoap.getSimpleIdentityWithUidAsync(SSOAuth.getSimpleIdentityWithUidRequest request)
        {
            return base.Channel.getSimpleIdentityWithUidAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSOAuth.getSimpleIdentityWithUidResponse> getSimpleIdentityWithUidAsync(string guid, string securityToken)
        {
            SSOAuth.getSimpleIdentityWithUidRequest inValue = new SSOAuth.getSimpleIdentityWithUidRequest();
            inValue.Body = new SSOAuth.getSimpleIdentityWithUidRequestBody();
            inValue.Body.guid = guid;
            inValue.Body.securityToken = securityToken;
            return ((SSOAuth.getIdentitySoap)(this)).getSimpleIdentityWithUidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSOAuth.getComplexIdentityResponse> SSOAuth.getIdentitySoap.getComplexIdentityAsync(SSOAuth.getComplexIdentityRequest request)
        {
            return base.Channel.getComplexIdentityAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSOAuth.getComplexIdentityResponse> getComplexIdentityAsync(string guid, string securityToken)
        {
            SSOAuth.getComplexIdentityRequest inValue = new SSOAuth.getComplexIdentityRequest();
            inValue.Body = new SSOAuth.getComplexIdentityRequestBody();
            inValue.Body.guid = guid;
            inValue.Body.securityToken = securityToken;
            return ((SSOAuth.getIdentitySoap)(this)).getComplexIdentityAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.getIdentitySoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.getIdentitySoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.getIdentitySoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ap2.pccu.edu.tw:8888/AssociatesService/SSO/getIdentity.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.getIdentitySoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ap2.pccu.edu.tw:8888/AssociatesService/SSO/getIdentity.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            getIdentitySoap,
            
            getIdentitySoap12,
        }
    }
}
